/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 4/08/2014, 05:14:02 PM
 */

package ControlUsuario;

import Entidades.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.Socket;
import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
//import org.uispec4j.Button;
//import org.uispec4j.TextBox;
//import org.uispec4j.Window;
/**
 *
 * @author Administrator2
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */

                static hilosEjecucion h;
                Usuario u;
     
    public VentanaPrincipal() {
//   try {
// UIManager.setLookAndFeel("org.lookAndFeels");
//
//} catch (ClassNotFoundException e) {
// e.printStackTrace();
//} catch (InstantiationException e) {
// e.printStackTrace();
//} catch (IllegalAccessException e) {
// e.printStackTrace();
//} catch (UnsupportedLookAndFeelException e) {
// e.printStackTrace();
//}

//      this.setUndecorated(true);//quita bordes a jframe

        initComponents();
        this.setVisible(true);
//        confi d = new confi(this);
//        jButton1.addActionListener(new no());
      
//        this.setDefaultCloseOperation( DO_NOTHING_ON_CLOSE  );//evita cerra jframe con ALT+C
//        this.setExtendedState( MAXIMIZED_BOTH );//maximizado
//        this.setAlwaysOnTop(true);//siempre al frente
////        nueva instancia de jBlocked pasando como parametros e este JFrame
//        new jBloqueo( this ).block();

//        usuario =  new Usuario();
//        c = new SesionUsuario(usuario);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        tpwPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("Usuario");

        lblContraseña.setText("Contraseña");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblUsuario)
                    .add(lblContraseña))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnEnviar)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(tpwPassword)
                        .add(txtUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 294, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(57, 57, 57)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblUsuario)
                    .add(txtUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(50, 50, 50)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblContraseña)
                    .add(tpwPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(35, 35, 35)
                .add(btnEnviar)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void s()
    {
        int i=0;
        while(i==0)
        {
            if(i!=0)
            {
                i=1;
            }else
            {
                i=0;
            }
        }
    }
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:

         // TODO add your handling code here:

        if(u==null)
        {
            u = new Usuario();
//            h = new hilosEjecucion();
        }

        //this.setVisible(false);

      
//        PropertyConfigurator.configure("log4j.properties");
//        String usuario = "yamit.cardozo";
//        String contraseña = "soporte.enf";

        String user = txtUsuario.getText();
        String pass = new String(tpwPassword.getPassword());
//        System.out.println(user);
//        usuario.setIdUsuario(user);
//        usuario.setContraseña(pass);
//        Calendar c1 = Calendar.getInstance();
//        servicioUsuario.setFechaInicio(c1.get(Calendar.DATE)+"/"+(c1.get((Calendar.MONTH))+1)+
//                "/"+c1.get(Calendar.YEAR)+"");
//        servicioUsuario.setHoraInicio(c1.get(Calendar.HOUR)+":"+c1.get(Calendar.MINUTE)+"");
//
//         creacion de hilo cliente
//        ConectorCliente c = new ConectorCliente(usuario);
//
//        c.iniciar();
//

        if(user.equals("") || pass.equals("")){
            JOptionPane.showMessageDialog(this, "campo vacio ingrese informacion solicitada");
        }else{
                 u.setIdUsuario(user);
                 u.setContraseña(pass);
                 h.setUsUsuario(u);
                 h.run();
                 u = h.getUsUsuario();
                 
                   String usuari = u.getIdUsuario();
                   String contraseñ = u.getContraseña();

                 // condiciones de valides

                if(usuari.equals(user)){

                    if(contraseñ.equals(pass)){

                        this.setVisible(false);
                        SesionUsuario q = new SesionUsuario();
//                        System.out.println("recivir");
//                        h.recibirMensajesServidor();
//                         System.out.println("recivir11");

                    }else{
                        JOptionPane.showMessageDialog(this, "contraseña incorrecta");
                    }  

                }else{
                    JOptionPane.showMessageDialog(this, "usuario no existe");
                }                
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

     /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try
            {
//                JFrame.setDefaultLookAndFeelDecorated(true);
//                JDialog.setDefaultLookAndFeelDecorated(true);
//              // UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//               // UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
//               // UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");      no encontro libreria
//                //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//                   //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
//                 // UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");  no encontro libreria
//                    //UIManager.setLookAndFeel( "com.apple.laf.AquaLookAndFeel");   no encontro libreria
//                   // UIManager.setLookAndFeel(  "com.sun.java.swing.plaf.mac.MacLookAndFeel");  no encontro libreria
//                       //     UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
////                    UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
//                //UIManager.setLookAndFeel(" org.jvnet.substance.skin.CremeSkin");
//                //SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.CremeCoffeeSkin");
//                UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");






            }
            catch (Exception e)
            {
                e.printStackTrace();
            }


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //VentanaPrincipal c = new VentanaPrincipal();
                 new VentanaPrincipal();
                 
            }
        });
                 h = new hilosEjecucion();
                 h.recibirMensajesServidor();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField tpwPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
