/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlUsuario;
/*
 * VentanaPrincipal1.java
 *
 * Created on 4/08/2014, 05:14:02 PM
 */

//package ControlUsuario;
//
//import controlUsuario.JOptionPaneConTimeOut;
//import java.awt.Image;
//import java.io.IOException;
//import javax.swing.ImageIcon;
//import javax.swing.JFrame;
//import javax.swing.JOptionPane;
//import javax.swing.UIManager;
//import org.jvnet.substance.skin.SubstanceMagmaLookAndFeel;
//import org.uispec4j.Button;
//import org.uispec4j.TextBox;
//import org.uispec4j.Window;
/**
 *
 * @author Administrator2
 */
public class VentanaPrincipal1 extends javax.swing.JFrame{

    /** Creates new form VentanaPrincipal1 */
//     static hilosEjecucion h = null;
//     static VentanaPrincipal1 f;
//      static fram frameAux = null;
//
//    public VentanaPrincipal1() {
//
//        lblImagen.setIcon(new ImageIcon(getClass().getResource("/Imagenes/lock.png")));
//
//        this.setUndecorated(true);
//        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//
//        initComponents();
//
//        btnEnviar.setIcon(new
//        javax.swing.ImageIcon(getClass().getResource("/Imagenes/next.png")));
//        lblImagen.setIcon(new
//        javax.swing.ImageIcon(getClass().getResource("/Imagenes/lock.png")));
//        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/images_1.png")).getImage());
//        this.setVisible(true);
//
//
//        lblImagen.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
//        btnEnviar.setIcon(new ImageIcon("/Imagenes/next.png"));
//        setIconImage(new Imagen("C:\\Users\\Elelegido\\Documents\\NetBeansProjects\\6.5\\RepositorioControlUsuario\\imagenes\\png\\16x16\\next.png"));
//                confi d = new confi(this);
//        jButton1.addActionListener(new no());
//
//        this.setDefaultCloseOperation( DO_NOTHING_ON_CLOSE  );//evita cerra jframe con ALT+C
//        this.setExtendedState( MAXIMIZED_BOTH );//maximizado
//        this.setAlwaysOnTop(true);//siempre al frente
//        nueva instancia de jBlocked pasando como parametros e este JFrame
//        new jBloqueo( this ).block();
//        txtUsuario.setEnabled(false);
//        tpwPassword.setEnabled(false);
//        btnEnviar.setEnabled(false);
//    }

//    private void setImagen()
//    {
//        lbl.setIcon(ajustarImagen("/home/beastieux/MiImagen.png"));
//        lbl.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
//    }
//
//   private void setImagen()
//    {
//        lbl.setIcon(ajustarImagen("x.png"));
//        lbl.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
//    }
//
//    private ImageIcon ajustarImagen(String ico)
//    {
//        ImageIcon tmpIconAux = new ImageIcon(ico);
//        Escalar Imagen
//        ImageIcon tmpIcon = new ImageIcon(tmpIconAux.getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
//        return tmpIcon;
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        tpwPassword = new javax.swing.JPasswordField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("Usuario");

        lblContraseña.setText("Contraseña");

        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lblContraseña)
                        .add(20, 20, 20)
                        .add(tpwPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(lblUsuario)
                        .add(63, 63, 63)
                        .add(txtUsuario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .add(503, 503, 503))
            .add(layout.createSequentialGroup()
                .add(156, 156, 156)
                .add(btnEnviar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(574, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .add(lblImagen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(64, 64, 64)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblUsuario))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblContraseña)
                    .add(tpwPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblImagen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(105, 105, 105)
                .add(btnEnviar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:

         // TODO add your handling code here:

//        String user = txtUsuario.getText();
//        String pass = new String(tpwPassword.getPassword());
//
//        if(user.equalsIgnoreCase("ocamilo.lopera") && pass.equalsIgnoreCase("1152439790"))
//        {
//            txtUsuario.setText("");
//            tpwPassword.setText("");
//            LanzadorImagen l = new LanzadorImagen(1,f);
////            h.enviarMensajeNoVisible();
//        }else if(user.equalsIgnoreCase("yamit.cardozo") && pass.equalsIgnoreCase("1038098543"))
//        {
//             txtUsuario.setText("");
//            tpwPassword.setText("");
//            LanzadorImagen l = new LanzadorImagen(1,f);
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(rootPane, "campo vacio ingrese informacion solicitada");
//        }
//        if(user.equals("") || pass.equals("")){
//            JOptionPane.showMessageDialog(null, "campo vacio ingrese informacion solicitada");
//        }else{
//                String usuari ="na";
//                String contraseñ = "na";
//                Usuario u=null;
////                hilosEjecucion h=null;
//
//            try {
//                System.out.println("entro");
//                h = new hilosEjecucion();
//
//                u = new Usuario();
//                   u.setIdUsuario(user);
//                 u.setContraseña(pass);
//
////                 h.setUsUsuario(u);
////                 h.run();
////                 u = h.getUsUsuario();
////
////                   usuari = u.getIdUsuario();
////                   contraseñ= u.getContraseña();
//                   System.out.println("entro1");
//
//            } catch (Exception ex) {
//                 System.out.println(usuari+"   "+ contraseñ);
//            }
//
//
//
//                 // condiciones de valides
//
//                if(usuari.equals(user)){
//
//                    if(contraseñ.equals(pass)){
//
//                        this.setVisible(false);
//                        SesionUsuario q = new SesionUsuario();
//                    try {
//                        h.recibirMensajesServidor();
//                    } catch (IOException ex) {
//                        Logger.getLogger(VentanaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//
//                    }else{
//                        JOptionPane.showMessageDialog(this, "contraseña incorrecta");
//                    }
//
//                }else{
//                    JOptionPane.showMessageDialog(this, "usuario no existe");
//                }
//        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

//       public static void  quitarPortal()
//    {
//        f.setVisible(false);
//        if(h!=null)
//        {
//        h.enviarMensajeNoVisible();
//        }
//    }
//
//    public static void colocarPortal()
//    {
//        f.setVisible(true);
//    }
//    public static boolean visible()
//    {
//        return f.isVisible();
//    }
//    public void cambiarImagenY(int numero)
//    {
//        lblImagen.setLocation(478, numero);
//    }
//     public void cambiarImagenX(int numero)
//    {
//
//        lblImagen.setLocation(numero, 200);
//    }
//     public void cambiarImagenUnlock()
//     {
////           lblImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elelegido\\Documents\\NetBeansProjects\\6.5\\RepositorioControlUsuario\\imagenes\\unlock.png"));
//            lblImagen.setIcon(new
//        javax.swing.ImageIcon(getClass().getResource("/Imagenes/unlock.png")));
//     }
//     public void cambiarImagenLock()
//     {
////         lblImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elelegido\\Documents\\NetBeansProjects\\6.5\\RepositorioControlUsuario\\imagenes\\lock.png"));
//         lblImagen.setIcon(new
//        javax.swing.ImageIcon(getClass().getResource("/Imagenes/lock.png")));
//     }
//     public void mostrarMensajeIp()
//     {
//         JOptionPane.showInternalMessageDialog(rootPane,"socket cerrado o no encotro servidor","conexion Socket",JOptionPane.ERROR_MESSAGE);
//     }
//     public static void mostrarMensajeChat(String mensaje)
//     {
//            if(frameAux==null){
//            frameAux = new fram();
//            }
//            JOptionPaneConTimeOut.visualizaDialogo(frameAux, mensaje,"mensaje chat" , 9000);
//         }
//     public static  void ApagarEquipo()
//     {
//         ejecucionexe("shutdown -s");
//     }
//     static  void ejecucionexe(String hilera){
//         try
//        {
//        Runtime.getRuntime().exec(hilera);
//        }
//         catch (SecurityException e)
//        {
//             e.fillInStackTrace();
//            // System.out.println("existe administrador de seguridad no puede crear subproceso");
//        }
//        catch (IOException e){
//            e.fillInStackTrace();
//            //System.out.println("error en el flujo de datos entrada o salida");
//        }
//        catch (NullPointerException e){
//            e.fillInStackTrace();
//            //System.out.println(" el comando de .exe es nulo");
//        }
//        catch(IllegalArgumentException e){
//            e.fillInStackTrace();
//            //System.out.println(" el comando de .exe esta vacio");
//        }
//    }
     /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        try
//            {
////            JFrame.setDefaultLookAndFeelDecorated(true);
////            SkinLookAndFeel.setSkin(SkinLookAndFeel.loadThemePack("temas/skins/silverLunaXPthemepack.zip"));
//            UIManager.setLookAndFeel(new SubstanceMagmaLookAndFeel());
////            SubstanceLookAndFeel.setSkin(new EmeraldDuskSkin());
//            }
//            catch (Exception e)
//            {
//                JOptionPane.showMessageDialog(null, e);
//            }
//
//        f = new VentanaPrincipal1();
//
//        int i=0;
//        do
//        {
//          h = new hilosEjecucion(f);
//          h.start();
//        try {
//            h.recibirMensajesServidor();
//        } catch ( IOException ex) {
//            System.out.println("streem null no puede seguir enviando datos main");
//            h.stop();
//            h = null;
//        }
//        }
//        while(i==0);
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField tpwPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables



}